# coding: utf-8

"""
    ESP Documentation

    The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import esp_sdk
from esp_sdk.rest import ApiException
from esp_sdk.apis.user_sso_api import UserSSOApi


class TestUserSSOApi(unittest.TestCase):
    """ UserSSOApi unit test stubs """

    def setUp(self):
        self.api = esp_sdk.apis.user_sso_api.UserSSOApi()

    def tearDown(self):
        pass

    def test_create(self):
        """
        Test case for create

        This endpoint is used to create a ESP JWT based on a Ping SSO token
        """
        pass

    def test_error(self):
        """
        Test case for error

        Displays a SAML error
        """
        pass

    def test_show(self):
        """
        Test case for show

        A successful call to this API redirects to the sso_url of the organization associated with a user.
        """
        pass


if __name__ == '__main__':
    unittest.main()
