# coding: utf-8

"""
    ESP Documentation

    The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import esp_sdk
from esp_sdk.rest import ApiException
from esp_sdk.apis.external_account_user_attribution_channels_api import ExternalAccountUserAttributionChannelsApi


class TestExternalAccountUserAttributionChannelsApi(unittest.TestCase):
    """ ExternalAccountUserAttributionChannelsApi unit test stubs """

    def setUp(self):
        self.api = esp_sdk.apis.external_account_user_attribution_channels_api.ExternalAccountUserAttributionChannelsApi()

    def tearDown(self):
        pass

    def test_create(self):
        """
        Test case for create

        A successful call to this API will create a User Attribution Channel for an external account.
        """
        pass

    def test_destroy(self):
        """
        Test case for destroy

        A successful call to this API will destrly the User Attribution Channel for an external account.
        """
        pass

    def test_show(self):
        """
        Test case for show

        A successful call to this API will show the User Attribution Channel of an external account.
        """
        pass


if __name__ == '__main__':
    unittest.main()
