# coding: utf-8

"""
    ESP Documentation

    The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.

    OpenAPI spec version: v2_sdk
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import esp_sdk
from esp_sdk.rest import ApiException
from esp_sdk.apis.report_export_api import ReportExportApi


class TestReportExportApi(unittest.TestCase):
    """ ReportExportApi unit test stubs """

    def setUp(self):
        self.api = esp_sdk.apis.report_export_api.ReportExportApi()

    def tearDown(self):
        pass

    def test_request_file(self):
        """
        Test case for request_file

        Export all alerts for a set of reports to a file
        """
        pass

    def test_send_to_integration(self):
        """
        Test case for send_to_integration

        Export all alerts on reports to an integration
        """
        pass

    def test_show_file_details(self):
        """
        Test case for show_file_details

        Show a single Exported Report
        """
        pass


if __name__ == '__main__':
    unittest.main()
