# coding: utf-8

"""
    ESP Documentation

    The Evident Security Platform API (version 2.0) is designed to allow users granular control over their Amazon Web Service security experience by allowing them to review alerts, monitor signatures, and create custom signatures.

    OpenAPI spec version: v2_sdk
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
from ..extensions.base_object import BaseObject
import re


class DashboardRegionStat(BaseObject):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, region=None, region_id=None, total_pass=None, total_fail=None, total_warn=None, total_error=None, total_info=None, total_high=None, total_medium=None, total_low=None, total_high_fail=None, total_high_error=None, total_high_warn=None, total_high_pass=None, total_high_info=None, total_medium_fail=None, total_medium_error=None, total_medium_warn=None, total_medium_pass=None, total_medium_info=None, total_low_fail=None, total_low_error=None, total_low_warn=None, total_low_pass=None, total_low_info=None, total_new_1h_high=None, total_new_1h_medium=None, total_new_1h_low=None, total_new_1d_high=None, total_new_1d_medium=None, total_new_1d_low=None, total_new_1d_pass=None, total_new_1d_fail=None, total_new_1d_warn=None, total_new_1d_error=None, total_new_1d_info=None, new_1d_high_fail=None, new_1d_high_error=None, new_1d_high_warn=None, new_1d_high_pass=None, new_1d_high_info=None, new_1d_medium_fail=None, new_1d_medium_error=None, new_1d_medium_warn=None, new_1d_medium_pass=None, new_1d_medium_info=None, new_1d_low_fail=None, new_1d_low_error=None, new_1d_low_warn=None, new_1d_low_pass=None, new_1d_low_info=None):
        """
        DashboardRegionStat - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'region': 'Region',
            'region_id': 'int',
            'total_pass': 'int',
            'total_fail': 'int',
            'total_warn': 'int',
            'total_error': 'int',
            'total_info': 'int',
            'total_high': 'int',
            'total_medium': 'int',
            'total_low': 'int',
            'total_high_fail': 'int',
            'total_high_error': 'int',
            'total_high_warn': 'int',
            'total_high_pass': 'int',
            'total_high_info': 'int',
            'total_medium_fail': 'int',
            'total_medium_error': 'int',
            'total_medium_warn': 'int',
            'total_medium_pass': 'int',
            'total_medium_info': 'int',
            'total_low_fail': 'int',
            'total_low_error': 'int',
            'total_low_warn': 'int',
            'total_low_pass': 'int',
            'total_low_info': 'int',
            'total_new_1h_high': 'int',
            'total_new_1h_medium': 'int',
            'total_new_1h_low': 'int',
            'total_new_1d_high': 'int',
            'total_new_1d_medium': 'int',
            'total_new_1d_low': 'int',
            'total_new_1d_pass': 'int',
            'total_new_1d_fail': 'int',
            'total_new_1d_warn': 'int',
            'total_new_1d_error': 'int',
            'total_new_1d_info': 'int',
            'new_1d_high_fail': 'int',
            'new_1d_high_error': 'int',
            'new_1d_high_warn': 'int',
            'new_1d_high_pass': 'int',
            'new_1d_high_info': 'int',
            'new_1d_medium_fail': 'int',
            'new_1d_medium_error': 'int',
            'new_1d_medium_warn': 'int',
            'new_1d_medium_pass': 'int',
            'new_1d_medium_info': 'int',
            'new_1d_low_fail': 'int',
            'new_1d_low_error': 'int',
            'new_1d_low_warn': 'int',
            'new_1d_low_pass': 'int',
            'new_1d_low_info': 'int'
        }

        self.attribute_map = {
            'region': 'region',
            'region_id': 'region_id',
            'total_pass': 'total_pass',
            'total_fail': 'total_fail',
            'total_warn': 'total_warn',
            'total_error': 'total_error',
            'total_info': 'total_info',
            'total_high': 'total_high',
            'total_medium': 'total_medium',
            'total_low': 'total_low',
            'total_high_fail': 'total_high_fail',
            'total_high_error': 'total_high_error',
            'total_high_warn': 'total_high_warn',
            'total_high_pass': 'total_high_pass',
            'total_high_info': 'total_high_info',
            'total_medium_fail': 'total_medium_fail',
            'total_medium_error': 'total_medium_error',
            'total_medium_warn': 'total_medium_warn',
            'total_medium_pass': 'total_medium_pass',
            'total_medium_info': 'total_medium_info',
            'total_low_fail': 'total_low_fail',
            'total_low_error': 'total_low_error',
            'total_low_warn': 'total_low_warn',
            'total_low_pass': 'total_low_pass',
            'total_low_info': 'total_low_info',
            'total_new_1h_high': 'total_new_1h_high',
            'total_new_1h_medium': 'total_new_1h_medium',
            'total_new_1h_low': 'total_new_1h_low',
            'total_new_1d_high': 'total_new_1d_high',
            'total_new_1d_medium': 'total_new_1d_medium',
            'total_new_1d_low': 'total_new_1d_low',
            'total_new_1d_pass': 'total_new_1d_pass',
            'total_new_1d_fail': 'total_new_1d_fail',
            'total_new_1d_warn': 'total_new_1d_warn',
            'total_new_1d_error': 'total_new_1d_error',
            'total_new_1d_info': 'total_new_1d_info',
            'new_1d_high_fail': 'new_1d_high_fail',
            'new_1d_high_error': 'new_1d_high_error',
            'new_1d_high_warn': 'new_1d_high_warn',
            'new_1d_high_pass': 'new_1d_high_pass',
            'new_1d_high_info': 'new_1d_high_info',
            'new_1d_medium_fail': 'new_1d_medium_fail',
            'new_1d_medium_error': 'new_1d_medium_error',
            'new_1d_medium_warn': 'new_1d_medium_warn',
            'new_1d_medium_pass': 'new_1d_medium_pass',
            'new_1d_medium_info': 'new_1d_medium_info',
            'new_1d_low_fail': 'new_1d_low_fail',
            'new_1d_low_error': 'new_1d_low_error',
            'new_1d_low_warn': 'new_1d_low_warn',
            'new_1d_low_pass': 'new_1d_low_pass',
            'new_1d_low_info': 'new_1d_low_info'
        }

        self._region = region
        self._region_id = region_id
        self._total_pass = total_pass
        self._total_fail = total_fail
        self._total_warn = total_warn
        self._total_error = total_error
        self._total_info = total_info
        self._total_high = total_high
        self._total_medium = total_medium
        self._total_low = total_low
        self._total_high_fail = total_high_fail
        self._total_high_error = total_high_error
        self._total_high_warn = total_high_warn
        self._total_high_pass = total_high_pass
        self._total_high_info = total_high_info
        self._total_medium_fail = total_medium_fail
        self._total_medium_error = total_medium_error
        self._total_medium_warn = total_medium_warn
        self._total_medium_pass = total_medium_pass
        self._total_medium_info = total_medium_info
        self._total_low_fail = total_low_fail
        self._total_low_error = total_low_error
        self._total_low_warn = total_low_warn
        self._total_low_pass = total_low_pass
        self._total_low_info = total_low_info
        self._total_new_1h_high = total_new_1h_high
        self._total_new_1h_medium = total_new_1h_medium
        self._total_new_1h_low = total_new_1h_low
        self._total_new_1d_high = total_new_1d_high
        self._total_new_1d_medium = total_new_1d_medium
        self._total_new_1d_low = total_new_1d_low
        self._total_new_1d_pass = total_new_1d_pass
        self._total_new_1d_fail = total_new_1d_fail
        self._total_new_1d_warn = total_new_1d_warn
        self._total_new_1d_error = total_new_1d_error
        self._total_new_1d_info = total_new_1d_info
        self._new_1d_high_fail = new_1d_high_fail
        self._new_1d_high_error = new_1d_high_error
        self._new_1d_high_warn = new_1d_high_warn
        self._new_1d_high_pass = new_1d_high_pass
        self._new_1d_high_info = new_1d_high_info
        self._new_1d_medium_fail = new_1d_medium_fail
        self._new_1d_medium_error = new_1d_medium_error
        self._new_1d_medium_warn = new_1d_medium_warn
        self._new_1d_medium_pass = new_1d_medium_pass
        self._new_1d_medium_info = new_1d_medium_info
        self._new_1d_low_fail = new_1d_low_fail
        self._new_1d_low_error = new_1d_low_error
        self._new_1d_low_warn = new_1d_low_warn
        self._new_1d_low_pass = new_1d_low_pass
        self._new_1d_low_info = new_1d_low_info

    @property
    def region(self):
        """
        Gets the region of this DashboardRegionStat.

        :return: The region of this DashboardRegionStat.
        :rtype: Region
        """
        return self._region

    @region.setter
    def region(self, region):
        """
        Sets the region of this DashboardRegionStat.

        :param region: The region of this DashboardRegionStat.
        :type: Region
        """

        self._region = region

    @property
    def region_id(self):
        """
        Gets the region_id of this DashboardRegionStat.

        :return: The region_id of this DashboardRegionStat.
        :rtype: int
        """
        return self._region_id

    @region_id.setter
    def region_id(self, region_id):
        """
        Sets the region_id of this DashboardRegionStat.

        :param region_id: The region_id of this DashboardRegionStat.
        :type: int
        """

        self._region_id = region_id

    @property
    def total_pass(self):
        """
        Gets the total_pass of this DashboardRegionStat.

        :return: The total_pass of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_pass

    @total_pass.setter
    def total_pass(self, total_pass):
        """
        Sets the total_pass of this DashboardRegionStat.

        :param total_pass: The total_pass of this DashboardRegionStat.
        :type: int
        """

        self._total_pass = total_pass

    @property
    def total_fail(self):
        """
        Gets the total_fail of this DashboardRegionStat.

        :return: The total_fail of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_fail

    @total_fail.setter
    def total_fail(self, total_fail):
        """
        Sets the total_fail of this DashboardRegionStat.

        :param total_fail: The total_fail of this DashboardRegionStat.
        :type: int
        """

        self._total_fail = total_fail

    @property
    def total_warn(self):
        """
        Gets the total_warn of this DashboardRegionStat.

        :return: The total_warn of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_warn

    @total_warn.setter
    def total_warn(self, total_warn):
        """
        Sets the total_warn of this DashboardRegionStat.

        :param total_warn: The total_warn of this DashboardRegionStat.
        :type: int
        """

        self._total_warn = total_warn

    @property
    def total_error(self):
        """
        Gets the total_error of this DashboardRegionStat.

        :return: The total_error of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_error

    @total_error.setter
    def total_error(self, total_error):
        """
        Sets the total_error of this DashboardRegionStat.

        :param total_error: The total_error of this DashboardRegionStat.
        :type: int
        """

        self._total_error = total_error

    @property
    def total_info(self):
        """
        Gets the total_info of this DashboardRegionStat.

        :return: The total_info of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_info

    @total_info.setter
    def total_info(self, total_info):
        """
        Sets the total_info of this DashboardRegionStat.

        :param total_info: The total_info of this DashboardRegionStat.
        :type: int
        """

        self._total_info = total_info

    @property
    def total_high(self):
        """
        Gets the total_high of this DashboardRegionStat.

        :return: The total_high of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_high

    @total_high.setter
    def total_high(self, total_high):
        """
        Sets the total_high of this DashboardRegionStat.

        :param total_high: The total_high of this DashboardRegionStat.
        :type: int
        """

        self._total_high = total_high

    @property
    def total_medium(self):
        """
        Gets the total_medium of this DashboardRegionStat.

        :return: The total_medium of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_medium

    @total_medium.setter
    def total_medium(self, total_medium):
        """
        Sets the total_medium of this DashboardRegionStat.

        :param total_medium: The total_medium of this DashboardRegionStat.
        :type: int
        """

        self._total_medium = total_medium

    @property
    def total_low(self):
        """
        Gets the total_low of this DashboardRegionStat.

        :return: The total_low of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_low

    @total_low.setter
    def total_low(self, total_low):
        """
        Sets the total_low of this DashboardRegionStat.

        :param total_low: The total_low of this DashboardRegionStat.
        :type: int
        """

        self._total_low = total_low

    @property
    def total_high_fail(self):
        """
        Gets the total_high_fail of this DashboardRegionStat.

        :return: The total_high_fail of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_high_fail

    @total_high_fail.setter
    def total_high_fail(self, total_high_fail):
        """
        Sets the total_high_fail of this DashboardRegionStat.

        :param total_high_fail: The total_high_fail of this DashboardRegionStat.
        :type: int
        """

        self._total_high_fail = total_high_fail

    @property
    def total_high_error(self):
        """
        Gets the total_high_error of this DashboardRegionStat.

        :return: The total_high_error of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_high_error

    @total_high_error.setter
    def total_high_error(self, total_high_error):
        """
        Sets the total_high_error of this DashboardRegionStat.

        :param total_high_error: The total_high_error of this DashboardRegionStat.
        :type: int
        """

        self._total_high_error = total_high_error

    @property
    def total_high_warn(self):
        """
        Gets the total_high_warn of this DashboardRegionStat.

        :return: The total_high_warn of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_high_warn

    @total_high_warn.setter
    def total_high_warn(self, total_high_warn):
        """
        Sets the total_high_warn of this DashboardRegionStat.

        :param total_high_warn: The total_high_warn of this DashboardRegionStat.
        :type: int
        """

        self._total_high_warn = total_high_warn

    @property
    def total_high_pass(self):
        """
        Gets the total_high_pass of this DashboardRegionStat.

        :return: The total_high_pass of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_high_pass

    @total_high_pass.setter
    def total_high_pass(self, total_high_pass):
        """
        Sets the total_high_pass of this DashboardRegionStat.

        :param total_high_pass: The total_high_pass of this DashboardRegionStat.
        :type: int
        """

        self._total_high_pass = total_high_pass

    @property
    def total_high_info(self):
        """
        Gets the total_high_info of this DashboardRegionStat.

        :return: The total_high_info of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_high_info

    @total_high_info.setter
    def total_high_info(self, total_high_info):
        """
        Sets the total_high_info of this DashboardRegionStat.

        :param total_high_info: The total_high_info of this DashboardRegionStat.
        :type: int
        """

        self._total_high_info = total_high_info

    @property
    def total_medium_fail(self):
        """
        Gets the total_medium_fail of this DashboardRegionStat.

        :return: The total_medium_fail of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_medium_fail

    @total_medium_fail.setter
    def total_medium_fail(self, total_medium_fail):
        """
        Sets the total_medium_fail of this DashboardRegionStat.

        :param total_medium_fail: The total_medium_fail of this DashboardRegionStat.
        :type: int
        """

        self._total_medium_fail = total_medium_fail

    @property
    def total_medium_error(self):
        """
        Gets the total_medium_error of this DashboardRegionStat.

        :return: The total_medium_error of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_medium_error

    @total_medium_error.setter
    def total_medium_error(self, total_medium_error):
        """
        Sets the total_medium_error of this DashboardRegionStat.

        :param total_medium_error: The total_medium_error of this DashboardRegionStat.
        :type: int
        """

        self._total_medium_error = total_medium_error

    @property
    def total_medium_warn(self):
        """
        Gets the total_medium_warn of this DashboardRegionStat.

        :return: The total_medium_warn of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_medium_warn

    @total_medium_warn.setter
    def total_medium_warn(self, total_medium_warn):
        """
        Sets the total_medium_warn of this DashboardRegionStat.

        :param total_medium_warn: The total_medium_warn of this DashboardRegionStat.
        :type: int
        """

        self._total_medium_warn = total_medium_warn

    @property
    def total_medium_pass(self):
        """
        Gets the total_medium_pass of this DashboardRegionStat.

        :return: The total_medium_pass of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_medium_pass

    @total_medium_pass.setter
    def total_medium_pass(self, total_medium_pass):
        """
        Sets the total_medium_pass of this DashboardRegionStat.

        :param total_medium_pass: The total_medium_pass of this DashboardRegionStat.
        :type: int
        """

        self._total_medium_pass = total_medium_pass

    @property
    def total_medium_info(self):
        """
        Gets the total_medium_info of this DashboardRegionStat.

        :return: The total_medium_info of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_medium_info

    @total_medium_info.setter
    def total_medium_info(self, total_medium_info):
        """
        Sets the total_medium_info of this DashboardRegionStat.

        :param total_medium_info: The total_medium_info of this DashboardRegionStat.
        :type: int
        """

        self._total_medium_info = total_medium_info

    @property
    def total_low_fail(self):
        """
        Gets the total_low_fail of this DashboardRegionStat.

        :return: The total_low_fail of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_low_fail

    @total_low_fail.setter
    def total_low_fail(self, total_low_fail):
        """
        Sets the total_low_fail of this DashboardRegionStat.

        :param total_low_fail: The total_low_fail of this DashboardRegionStat.
        :type: int
        """

        self._total_low_fail = total_low_fail

    @property
    def total_low_error(self):
        """
        Gets the total_low_error of this DashboardRegionStat.

        :return: The total_low_error of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_low_error

    @total_low_error.setter
    def total_low_error(self, total_low_error):
        """
        Sets the total_low_error of this DashboardRegionStat.

        :param total_low_error: The total_low_error of this DashboardRegionStat.
        :type: int
        """

        self._total_low_error = total_low_error

    @property
    def total_low_warn(self):
        """
        Gets the total_low_warn of this DashboardRegionStat.

        :return: The total_low_warn of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_low_warn

    @total_low_warn.setter
    def total_low_warn(self, total_low_warn):
        """
        Sets the total_low_warn of this DashboardRegionStat.

        :param total_low_warn: The total_low_warn of this DashboardRegionStat.
        :type: int
        """

        self._total_low_warn = total_low_warn

    @property
    def total_low_pass(self):
        """
        Gets the total_low_pass of this DashboardRegionStat.

        :return: The total_low_pass of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_low_pass

    @total_low_pass.setter
    def total_low_pass(self, total_low_pass):
        """
        Sets the total_low_pass of this DashboardRegionStat.

        :param total_low_pass: The total_low_pass of this DashboardRegionStat.
        :type: int
        """

        self._total_low_pass = total_low_pass

    @property
    def total_low_info(self):
        """
        Gets the total_low_info of this DashboardRegionStat.

        :return: The total_low_info of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_low_info

    @total_low_info.setter
    def total_low_info(self, total_low_info):
        """
        Sets the total_low_info of this DashboardRegionStat.

        :param total_low_info: The total_low_info of this DashboardRegionStat.
        :type: int
        """

        self._total_low_info = total_low_info

    @property
    def total_new_1h_high(self):
        """
        Gets the total_new_1h_high of this DashboardRegionStat.

        :return: The total_new_1h_high of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1h_high

    @total_new_1h_high.setter
    def total_new_1h_high(self, total_new_1h_high):
        """
        Sets the total_new_1h_high of this DashboardRegionStat.

        :param total_new_1h_high: The total_new_1h_high of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1h_high = total_new_1h_high

    @property
    def total_new_1h_medium(self):
        """
        Gets the total_new_1h_medium of this DashboardRegionStat.

        :return: The total_new_1h_medium of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1h_medium

    @total_new_1h_medium.setter
    def total_new_1h_medium(self, total_new_1h_medium):
        """
        Sets the total_new_1h_medium of this DashboardRegionStat.

        :param total_new_1h_medium: The total_new_1h_medium of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1h_medium = total_new_1h_medium

    @property
    def total_new_1h_low(self):
        """
        Gets the total_new_1h_low of this DashboardRegionStat.

        :return: The total_new_1h_low of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1h_low

    @total_new_1h_low.setter
    def total_new_1h_low(self, total_new_1h_low):
        """
        Sets the total_new_1h_low of this DashboardRegionStat.

        :param total_new_1h_low: The total_new_1h_low of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1h_low = total_new_1h_low

    @property
    def total_new_1d_high(self):
        """
        Gets the total_new_1d_high of this DashboardRegionStat.

        :return: The total_new_1d_high of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1d_high

    @total_new_1d_high.setter
    def total_new_1d_high(self, total_new_1d_high):
        """
        Sets the total_new_1d_high of this DashboardRegionStat.

        :param total_new_1d_high: The total_new_1d_high of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1d_high = total_new_1d_high

    @property
    def total_new_1d_medium(self):
        """
        Gets the total_new_1d_medium of this DashboardRegionStat.

        :return: The total_new_1d_medium of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1d_medium

    @total_new_1d_medium.setter
    def total_new_1d_medium(self, total_new_1d_medium):
        """
        Sets the total_new_1d_medium of this DashboardRegionStat.

        :param total_new_1d_medium: The total_new_1d_medium of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1d_medium = total_new_1d_medium

    @property
    def total_new_1d_low(self):
        """
        Gets the total_new_1d_low of this DashboardRegionStat.

        :return: The total_new_1d_low of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1d_low

    @total_new_1d_low.setter
    def total_new_1d_low(self, total_new_1d_low):
        """
        Sets the total_new_1d_low of this DashboardRegionStat.

        :param total_new_1d_low: The total_new_1d_low of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1d_low = total_new_1d_low

    @property
    def total_new_1d_pass(self):
        """
        Gets the total_new_1d_pass of this DashboardRegionStat.

        :return: The total_new_1d_pass of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1d_pass

    @total_new_1d_pass.setter
    def total_new_1d_pass(self, total_new_1d_pass):
        """
        Sets the total_new_1d_pass of this DashboardRegionStat.

        :param total_new_1d_pass: The total_new_1d_pass of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1d_pass = total_new_1d_pass

    @property
    def total_new_1d_fail(self):
        """
        Gets the total_new_1d_fail of this DashboardRegionStat.

        :return: The total_new_1d_fail of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1d_fail

    @total_new_1d_fail.setter
    def total_new_1d_fail(self, total_new_1d_fail):
        """
        Sets the total_new_1d_fail of this DashboardRegionStat.

        :param total_new_1d_fail: The total_new_1d_fail of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1d_fail = total_new_1d_fail

    @property
    def total_new_1d_warn(self):
        """
        Gets the total_new_1d_warn of this DashboardRegionStat.

        :return: The total_new_1d_warn of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1d_warn

    @total_new_1d_warn.setter
    def total_new_1d_warn(self, total_new_1d_warn):
        """
        Sets the total_new_1d_warn of this DashboardRegionStat.

        :param total_new_1d_warn: The total_new_1d_warn of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1d_warn = total_new_1d_warn

    @property
    def total_new_1d_error(self):
        """
        Gets the total_new_1d_error of this DashboardRegionStat.

        :return: The total_new_1d_error of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1d_error

    @total_new_1d_error.setter
    def total_new_1d_error(self, total_new_1d_error):
        """
        Sets the total_new_1d_error of this DashboardRegionStat.

        :param total_new_1d_error: The total_new_1d_error of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1d_error = total_new_1d_error

    @property
    def total_new_1d_info(self):
        """
        Gets the total_new_1d_info of this DashboardRegionStat.

        :return: The total_new_1d_info of this DashboardRegionStat.
        :rtype: int
        """
        return self._total_new_1d_info

    @total_new_1d_info.setter
    def total_new_1d_info(self, total_new_1d_info):
        """
        Sets the total_new_1d_info of this DashboardRegionStat.

        :param total_new_1d_info: The total_new_1d_info of this DashboardRegionStat.
        :type: int
        """

        self._total_new_1d_info = total_new_1d_info

    @property
    def new_1d_high_fail(self):
        """
        Gets the new_1d_high_fail of this DashboardRegionStat.

        :return: The new_1d_high_fail of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_high_fail

    @new_1d_high_fail.setter
    def new_1d_high_fail(self, new_1d_high_fail):
        """
        Sets the new_1d_high_fail of this DashboardRegionStat.

        :param new_1d_high_fail: The new_1d_high_fail of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_high_fail = new_1d_high_fail

    @property
    def new_1d_high_error(self):
        """
        Gets the new_1d_high_error of this DashboardRegionStat.

        :return: The new_1d_high_error of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_high_error

    @new_1d_high_error.setter
    def new_1d_high_error(self, new_1d_high_error):
        """
        Sets the new_1d_high_error of this DashboardRegionStat.

        :param new_1d_high_error: The new_1d_high_error of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_high_error = new_1d_high_error

    @property
    def new_1d_high_warn(self):
        """
        Gets the new_1d_high_warn of this DashboardRegionStat.

        :return: The new_1d_high_warn of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_high_warn

    @new_1d_high_warn.setter
    def new_1d_high_warn(self, new_1d_high_warn):
        """
        Sets the new_1d_high_warn of this DashboardRegionStat.

        :param new_1d_high_warn: The new_1d_high_warn of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_high_warn = new_1d_high_warn

    @property
    def new_1d_high_pass(self):
        """
        Gets the new_1d_high_pass of this DashboardRegionStat.

        :return: The new_1d_high_pass of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_high_pass

    @new_1d_high_pass.setter
    def new_1d_high_pass(self, new_1d_high_pass):
        """
        Sets the new_1d_high_pass of this DashboardRegionStat.

        :param new_1d_high_pass: The new_1d_high_pass of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_high_pass = new_1d_high_pass

    @property
    def new_1d_high_info(self):
        """
        Gets the new_1d_high_info of this DashboardRegionStat.

        :return: The new_1d_high_info of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_high_info

    @new_1d_high_info.setter
    def new_1d_high_info(self, new_1d_high_info):
        """
        Sets the new_1d_high_info of this DashboardRegionStat.

        :param new_1d_high_info: The new_1d_high_info of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_high_info = new_1d_high_info

    @property
    def new_1d_medium_fail(self):
        """
        Gets the new_1d_medium_fail of this DashboardRegionStat.

        :return: The new_1d_medium_fail of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_medium_fail

    @new_1d_medium_fail.setter
    def new_1d_medium_fail(self, new_1d_medium_fail):
        """
        Sets the new_1d_medium_fail of this DashboardRegionStat.

        :param new_1d_medium_fail: The new_1d_medium_fail of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_medium_fail = new_1d_medium_fail

    @property
    def new_1d_medium_error(self):
        """
        Gets the new_1d_medium_error of this DashboardRegionStat.

        :return: The new_1d_medium_error of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_medium_error

    @new_1d_medium_error.setter
    def new_1d_medium_error(self, new_1d_medium_error):
        """
        Sets the new_1d_medium_error of this DashboardRegionStat.

        :param new_1d_medium_error: The new_1d_medium_error of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_medium_error = new_1d_medium_error

    @property
    def new_1d_medium_warn(self):
        """
        Gets the new_1d_medium_warn of this DashboardRegionStat.

        :return: The new_1d_medium_warn of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_medium_warn

    @new_1d_medium_warn.setter
    def new_1d_medium_warn(self, new_1d_medium_warn):
        """
        Sets the new_1d_medium_warn of this DashboardRegionStat.

        :param new_1d_medium_warn: The new_1d_medium_warn of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_medium_warn = new_1d_medium_warn

    @property
    def new_1d_medium_pass(self):
        """
        Gets the new_1d_medium_pass of this DashboardRegionStat.

        :return: The new_1d_medium_pass of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_medium_pass

    @new_1d_medium_pass.setter
    def new_1d_medium_pass(self, new_1d_medium_pass):
        """
        Sets the new_1d_medium_pass of this DashboardRegionStat.

        :param new_1d_medium_pass: The new_1d_medium_pass of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_medium_pass = new_1d_medium_pass

    @property
    def new_1d_medium_info(self):
        """
        Gets the new_1d_medium_info of this DashboardRegionStat.

        :return: The new_1d_medium_info of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_medium_info

    @new_1d_medium_info.setter
    def new_1d_medium_info(self, new_1d_medium_info):
        """
        Sets the new_1d_medium_info of this DashboardRegionStat.

        :param new_1d_medium_info: The new_1d_medium_info of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_medium_info = new_1d_medium_info

    @property
    def new_1d_low_fail(self):
        """
        Gets the new_1d_low_fail of this DashboardRegionStat.

        :return: The new_1d_low_fail of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_low_fail

    @new_1d_low_fail.setter
    def new_1d_low_fail(self, new_1d_low_fail):
        """
        Sets the new_1d_low_fail of this DashboardRegionStat.

        :param new_1d_low_fail: The new_1d_low_fail of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_low_fail = new_1d_low_fail

    @property
    def new_1d_low_error(self):
        """
        Gets the new_1d_low_error of this DashboardRegionStat.

        :return: The new_1d_low_error of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_low_error

    @new_1d_low_error.setter
    def new_1d_low_error(self, new_1d_low_error):
        """
        Sets the new_1d_low_error of this DashboardRegionStat.

        :param new_1d_low_error: The new_1d_low_error of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_low_error = new_1d_low_error

    @property
    def new_1d_low_warn(self):
        """
        Gets the new_1d_low_warn of this DashboardRegionStat.

        :return: The new_1d_low_warn of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_low_warn

    @new_1d_low_warn.setter
    def new_1d_low_warn(self, new_1d_low_warn):
        """
        Sets the new_1d_low_warn of this DashboardRegionStat.

        :param new_1d_low_warn: The new_1d_low_warn of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_low_warn = new_1d_low_warn

    @property
    def new_1d_low_pass(self):
        """
        Gets the new_1d_low_pass of this DashboardRegionStat.

        :return: The new_1d_low_pass of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_low_pass

    @new_1d_low_pass.setter
    def new_1d_low_pass(self, new_1d_low_pass):
        """
        Sets the new_1d_low_pass of this DashboardRegionStat.

        :param new_1d_low_pass: The new_1d_low_pass of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_low_pass = new_1d_low_pass

    @property
    def new_1d_low_info(self):
        """
        Gets the new_1d_low_info of this DashboardRegionStat.

        :return: The new_1d_low_info of this DashboardRegionStat.
        :rtype: int
        """
        return self._new_1d_low_info

    @new_1d_low_info.setter
    def new_1d_low_info(self, new_1d_low_info):
        """
        Sets the new_1d_low_info of this DashboardRegionStat.

        :param new_1d_low_info: The new_1d_low_info of this DashboardRegionStat.
        :type: int
        """

        self._new_1d_low_info = new_1d_low_info

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DashboardRegionStat):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
